# Generated by Django 5.2.7 on 2025-10-27 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la tarea (mínimo 3 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción detallada de la tarea', verbose_name='Descripción')),
                ('completed', models.BooleanField(default=False, help_text='Indica si la tarea está completada', verbose_name='Completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la tarea', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='task_created_idx'), models.Index(fields=['completed'], name='task_completed_idx')],
            },
        ),
    ]
